user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 1313;
        server_name localhost;

        location / {
            root /home/static;
            index index.html index.htm;
            # Add rules like this
            # if ($query_string = "p=2") {
            #    return 302 /about/;
            # }
            
            if ($query_string = "p=1") { return 302 /uncategorized/coding/; }
            if ($query_string = "p=271") { return 302 /uncategorized/airtable-data-management-and-collaboration/; }
            if ($query_string = "p=453") { return 302 /uncategorized/tableau-inquiring-far-and-beyond-with-data-visualization/; }
            if ($query_string = "page_id=9") { return 302 /; }
            if ($query_string = "page_id=992") { return 302 /an-imagined-geography-of-empire/; }
            if ($query_string = "page_id=1287") { return 302 /cv/; }
            if ($query_string = "p=177") { return 302 /uncategorized/omeka-curatorship-and-exhibits-in-the-digital-age/; }
            if ($query_string = "p=363") { return 302 /uncategorized/voyant-and-text-mining-when-quantitative-meets-qualitative/; }
            if ($query_string = "p=366") { return 302 /uncategorized/palladio-everything-is-connected/; }
            if ($query_string = "p=758") { return 302 /uncategorized/risky-new-york/; }
            if ($query_string = "page_id=3") { return 302 /; }
            if ($query_string = "page_id=150") { return 302 /contact-me/; }
            if ($query_string = "page_id=632") { return 302 /worlds-fairs-of-america-data-biography/; }
            if ($query_string = "p=66") { return 302 /uncategorized/zotero/; }
            if ($query_string = "p=291") { return 302 /uncategorized/storymaps-a-place-based-form-of-historical-narrative/; }
            if ($query_string = "page_id=181") { return 302 /research-tools/; }
            if ($query_string = "page_id=487") { return 302 /scholarship/; }
            if ($query_string = "page_id=493") { return 302 /presentations/; }
            if ($query_string = "p=160") { return 302 /uncategorized/organize-your-mess-tropy-and-historical-research/; }
            if ($query_string = "page_id=2") { return 302 /blog/; }
            if ($query_string = "page_id=185") { return 302 /communication-tools/; }
            if ($query_string = "page_id=189") { return 302 /visualization-tools/; }
        }
    }
}
